import type {Metadata} from "next";
import {League_Spartan} from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";

const League = League_Spartan({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={League.className}>{children}</body>
      </html>
    </Providers>
  );
}
